import { getDb } from "@/lib/db";

export const dynamic = "force-dynamic";

type StoreSettings={store_name:string;logo_url:string|null;primary_color:string|null;top_message:string|null;disclosure_text:string|null;price_notice:string|null};
type Product={id:number;name:string;description:string|null;regular_price:string|null;promo_price:string|null;destination_url:string|null;affiliate_url:string|null;sale_mode:string|null;product_type:string|null;platform:string|null;button_text:string|null;image_url:string|null;category_name:string|null;category_slug:string|null};
type Category={id:number;name:string;slug:string;product_count:number};
type Banner={id:number;title:string|null;subtitle:string|null;image_url:string;target_url:string|null};
function money(v:string|null){if(!v)return null;const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n):null;}
function platformLabel(v:string|null){const x:Record<string,string>={mercado_livre:"Mercado Livre",shopee:"Shopee",amazon:"Amazon",hotmart:"Hotmart",proprio:"SHILMASTORE",outra:"Outra"};return v?x[v]||v:"";}
export default async function Home({searchParams}:{searchParams:Promise<{q?:string;categoria?:string}>}){
 const params=await searchParams; const q=String(params.q||"").trim(); const categoria=String(params.categoria||"").trim(); const sql=getDb();
 const [sr,products,categories,banners]=await Promise.all([
  sql`SELECT store_name,logo_url,primary_color,top_message,disclosure_text,price_notice FROM store_settings WHERE id=1 LIMIT 1`,
  sql`SELECT p.id,p.name,p.description,p.regular_price,p.promo_price,p.destination_url,p.affiliate_url,p.sale_mode,p.product_type,p.platform,p.button_text,c.name category_name,c.slug category_slug,(SELECT pi.image_url FROM product_images pi WHERE pi.product_id=p.id ORDER BY pi.sort_order,pi.id LIMIT 1) image_url FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.active=TRUE AND (${q}='' OR p.name ILIKE ${'%'+q+'%'} OR COALESCE(p.description,'') ILIKE ${'%'+q+'%'}) AND (${categoria}='' OR c.slug=${categoria}) ORDER BY p.featured DESC,p.sort_order,p.updated_at DESC`,
  sql`SELECT c.id,c.name,c.slug,COUNT(p.id)::int product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id AND p.active=TRUE WHERE c.active=TRUE GROUP BY c.id,c.name,c.slug ORDER BY c.sort_order,c.name`,
  sql`SELECT id,title,subtitle,image_url,target_url FROM banners WHERE active=TRUE AND (starts_at IS NULL OR starts_at<=NOW()) AND (expires_at IS NULL OR expires_at>=NOW()) ORDER BY sort_order,updated_at DESC LIMIT 1`
 ]);
 const s=sr[0] as StoreSettings|undefined; const store=s?.store_name&&s.store_name!=="Radar de Achados"?s.store_name:"SHILMASTORE"; const primary=s?.primary_color||"#3483FA"; const list=products as Product[]; const cats=categories as Category[]; const banner=(banners as Banner[])[0];
 const categoryHref=(slug:string)=>`/?categoria=${encodeURIComponent(slug)}#ofertas`;
 return <main style={{minHeight:"100vh",background:"#f3f4f6",color:"#172554"}}>
  <div style={{background:"#0b2a55",color:"white",textAlign:"center",padding:"6px 16px",fontSize:12,fontWeight:800}}>{s?.top_message||"Ofertas selecionadas para você economizar de verdade!"}</div>
  <header style={{background:"#ffe600"}}><div style={{maxWidth:1200,margin:"auto",padding:"14px 22px 10px",display:"grid",gridTemplateColumns:"minmax(210px,.8fr) minmax(300px,1.7fr)",gap:24,alignItems:"center"}}><a href="/" style={{display:"flex",gap:11,alignItems:"center",textDecoration:"none",color:"#172554"}}>{s?.logo_url?<img src={s.logo_url} alt={store} style={{width:50,height:50,objectFit:"contain",background:"white",borderRadius:10}}/>:<span style={{width:48,height:48,display:"grid",placeItems:"center",borderRadius:11,background:primary,color:"white",fontWeight:900}}>SS</span>}<span><b style={{fontSize:23}}>{store}</b><small style={{display:"block",fontWeight:700}}>Produtos e ofertas em um só lugar</small></span></a><form action="/" method="get" style={{display:"flex",background:"white",borderRadius:7,boxShadow:"0 1px 5px #0002",overflow:"hidden"}}><input name="q" defaultValue={q} placeholder="Buscar produtos, marcas e ofertas..." style={{flex:1,minWidth:0,border:0,outline:0,padding:"14px 16px",fontSize:15}}/><button aria-label="Buscar" style={{width:54,border:0,borderLeft:"1px solid #eee",background:"white",fontSize:20,cursor:"pointer"}}>⌕</button></form></div><nav style={{maxWidth:1200,margin:"auto",padding:"0 22px 12px",display:"flex",gap:20,overflowX:"auto",fontSize:13,fontWeight:700}}><a href="/" style={{color:"#172554",textDecoration:"none",whiteSpace:"nowrap"}}>Início</a><a href="#ofertas" style={{color:"#172554",textDecoration:"none",whiteSpace:"nowrap"}}>Ofertas</a>{cats.map(c=><a key={c.id} href={categoryHref(c.slug)} style={{color:"#172554",textDecoration:"none",whiteSpace:"nowrap"}}>{c.name}</a>)}</nav></header>
  <section style={{maxWidth:1200,margin:"18px auto 0",padding:"0 22px"}}>{banner?<a href={banner.target_url||"#ofertas"} target={banner.target_url?"_blank":undefined} rel={banner.target_url?"noopener noreferrer":undefined} style={{display:"block",position:"relative",borderRadius:14,overflow:"hidden",background:"#e5e7eb",aspectRatio:"936 / 260"}}><img src={banner.image_url} alt={banner.title||"Oferta SHILMASTORE"} style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/>{banner.title?<div style={{position:"absolute",left:28,bottom:24,background:"rgba(11,42,85,.9)",color:"white",padding:"12px 16px",borderRadius:9,maxWidth:430}}><b style={{fontSize:20}}>{banner.title}</b>{banner.subtitle?<span style={{display:"block",marginTop:3,fontSize:13}}>{banner.subtitle}</span>:null}</div>:null}</a>:<div style={{borderRadius:14,background:"linear-gradient(100deg,#ffe600,#fff27a)",padding:"32px 38px",display:"flex",justifyContent:"space-between",alignItems:"center",gap:20}}><div><small style={{fontWeight:900,color:"#174ea6"}}>DESTAQUES SHILMASTORE</small><h1 style={{fontSize:"clamp(28px,4vw,44px)",margin:"5px 0"}}>Ofertas para você</h1><p style={{margin:0,color:"#475569"}}>Produtos próprios e achados de parceiros reunidos em um só lugar.</p></div><a href="#ofertas" style={{background:"#174ea6",color:"white",padding:"12px 18px",borderRadius:9,fontWeight:900,textDecoration:"none"}}>Ver ofertas</a></div>}</section>
  <section id="ofertas" style={{maxWidth:1200,margin:"auto",padding:"28px 22px 48px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,marginBottom:16,flexWrap:"wrap"}}><div><h2 style={{fontSize:28,margin:"0 0 4px"}}>{q?`Resultados para “${q}”`:categoria?"Produtos da categoria":"Ofertas em destaque"}</h2><span style={{fontSize:13,color:"#64748b"}}>{list.length} produto{list.length===1?"":"s"}</span></div>{(q||categoria)?<a href="/#ofertas" style={{fontSize:13,fontWeight:800,color:primary}}>Limpar filtros</a>:null}</div>
   {list.length===0?<div style={{background:"white",padding:38,borderRadius:14,textAlign:"center"}}><b>Nenhum produto encontrado.</b><p style={{color:"#64748b"}}>Tente outra busca ou veja todas as ofertas.</p></div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(190px,1fr))",gap:14}}>{list.map(p=>{const current=money(p.promo_price)||money(p.regular_price);const old=p.promo_price?money(p.regular_price):null;const dest=p.destination_url||p.affiliate_url;return <article key={p.id} style={{background:"white",borderRadius:12,overflow:"hidden",border:"1px solid #e5e7eb",display:"flex",flexDirection:"column",maxWidth:260}}><div style={{height:190,display:"grid",placeItems:"center",padding:12,borderBottom:"1px solid #eee"}}>{p.image_url?<img src={p.image_url} alt={p.name} style={{maxWidth:"92%",maxHeight:170,objectFit:"contain"}}/>:<span>Sem imagem</span>}</div><div style={{padding:14,display:"flex",flexDirection:"column",gap:7,flex:1}}><small style={{fontWeight:900,color:primary,textTransform:"uppercase"}}>{p.category_name||platformLabel(p.platform)}</small><h3 style={{fontSize:15,lineHeight:1.3,margin:0}}>{p.name}</h3>{p.description?<p style={{fontSize:12,color:"#64748b",lineHeight:1.35,margin:0}}>{p.description}</p>:null}<div style={{marginTop:"auto"}}>{old?<small style={{color:"#94a3b8",textDecoration:"line-through"}}>{old}</small>:null}<strong style={{display:"block",fontSize:21,color:"#111827"}}>{current||"Consulte"}</strong></div>{dest?<a href={`/go/${p.id}?source=site`} target="_blank" rel="noopener noreferrer sponsored" style={{background:primary,color:"white",textAlign:"center",padding:"10px",borderRadius:7,textDecoration:"none",fontWeight:900}}>{p.button_text||"Ver oferta"}</a>:null}</div></article>})}</div>}
  </section>
  <footer style={{background:"white",borderTop:"1px solid #ddd"}}><div style={{maxWidth:1200,margin:"auto",padding:"24px 22px",display:"flex",justifyContent:"space-between",gap:28,flexWrap:"wrap",fontSize:12,color:"#64748b"}}><div><b style={{fontSize:16,color:"#172554"}}>{store}</b><div>Produtos e ofertas em um só lugar.</div></div><div style={{maxWidth:650}}>{s?.disclosure_text&&!s.disclosure_text.includes("Radar de Achados")?s.disclosure_text:"Alguns links podem ser de afiliados. A SHILMASTORE pode receber comissão por compras qualificadas, sem custo adicional para você."}<div>{s?.price_notice||"Preços e disponibilidade podem mudar sem aviso prévio."}</div></div></div></footer>
 </main>;
}
