import { getDb } from "@/lib/db";
import { notFound,redirect } from "next/navigation";
export const dynamic="force-dynamic";
function localInput(value:unknown){if(!value)return "";const d=new Date(String(value));if(Number.isNaN(d.getTime()))return "";const parts=new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Fortaleza",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(d);const get=(t:string)=>parts.find(p=>p.type===t)?.value||"";return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`;}
function parseDate(value:FormDataEntryValue|null){const raw=String(value||"").trim();if(!raw)return null;const date=new Date(raw);return Number.isNaN(date.getTime())?null:date;}
async function getCoupon(id:number){const sql=getDb();const rows=await sql`SELECT id,product_id,code,description,starts_at,expires_at,active FROM coupons WHERE id=${id} LIMIT 1`;return rows[0]||null;}
async function getProducts(){const sql=getDb();return sql`SELECT id,name FROM products ORDER BY name`;}
async function updateCoupon(formData:FormData){"use server";const id=Number(formData.get("id"));const code=String(formData.get("code")||"").trim().toUpperCase();const description=String(formData.get("description")||"").trim();const productRaw=String(formData.get("product_id")||"").trim();const productId=productRaw?Number(productRaw):null;const startsAt=parseDate(formData.get("starts_at"));const expiresAt=parseDate(formData.get("expires_at"));const active=formData.get("active")==="on";if(!Number.isInteger(id)||id<=0||!code)throw new Error("Cupom inválido.");if(startsAt&&expiresAt&&expiresAt<=startsAt)throw new Error("A validade final deve ser posterior ao início.");const sql=getDb();await sql`UPDATE coupons SET product_id=${productId},code=${code},description=${description||null},starts_at=${startsAt},expires_at=${expiresAt},active=${active},updated_at=NOW() WHERE id=${id}`;redirect("/admin/cupons");}
export default async function EditarCupomPage({params}:{params:Promise<{id:string}>}){const {id:raw}=await params;const id=Number(raw);if(!Number.isInteger(id)||id<=0)notFound();const coupon:any=await getCoupon(id);if(!coupon)notFound();const products:any[]=await getProducts() as any[];return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span className="admin-logo">RA</span><div><strong>Radar de Achados</strong><small>Painel 2.0</small></div></div><nav className="admin-nav"><a href="/admin">Visão geral</a><a href="/admin/produtos">Produtos</a><a href="/admin/categorias">Categorias</a><a className="active" href="/admin/cupons">Cupons</a><span>Banners</span><span>Cliques</span><span>Configurações</span></nav></aside><section className="admin-content"><header className="admin-header"><div><p className="eyebrow">OFERTAS</p><h1>Editar cupom</h1><p className="admin-subtitle">Atualize o cupom e sua vinculação com produtos.</p></div><a className="secondary-button" href="/admin/cupons">← Voltar</a></header><form action={updateCoupon} className="product-form"><input type="hidden" name="id" value={coupon.id}/><section className="form-card"><div className="form-grid two-columns"><label className="field"><span>Código *</span><input name="code" required defaultValue={coupon.code}/></label><label className="field"><span>Produto</span><select name="product_id" defaultValue={coupon.product_id?String(coupon.product_id):""}><option value="">Cupom geral — sem produto específico</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field field-full"><span>Descrição</span><input name="description" defaultValue={coupon.description||""}/></label><label className="field"><span>Início</span><input type="datetime-local" name="starts_at" defaultValue={localInput(coupon.starts_at)}/></label><label className="field"><span>Validade</span><input type="datetime-local" name="expires_at" defaultValue={localInput(coupon.expires_at)}/></label><div className="check-fields field-full"><label><input type="checkbox" name="active" defaultChecked={Boolean(coupon.active)}/> Cupom ativo</label></div></div></section><div className="form-actions"><a className="secondary-button" href="/admin/cupons">Cancelar</a><button className="primary-button" type="submit">Salvar alterações</button></div></form></section></main>;}
