import { NextResponse } from "next/server";
import { getMercadoLivreAccessToken } from "@/lib/mercadolivre";

export const dynamic = "force-dynamic";

type MercadoLivreProduct = { id?: string; name?: string; status?: string; domain_id?: string; pictures?: Array<{ id?: string; url?: string; secure_url?: string }>; main_features?: Array<{ text?: string; value_name?: string }> };
type MercadoLivreOffer = { item_id?: string; price?: number; original_price?: number | null; currency_id?: string; condition?: string };
type DomainSuggestion = { domain_id?: string; domain_name?: string; category_id?: string; category_name?: string };
type SearchRow = { id:string|null; name:string|null; status:string|null; domain_id:string|null; image:string|null; pictures:string[]; features:string[]; permalink:string|null; offer_item_id:string|null; offer_price:number|null; offer_original_price:number|null; currency_id:string|null; offers_count:number; search_position:number; relevance:number; coverage:number };

async function mlFetch(url:string){let token=await getMercadoLivreAccessToken();let response=await fetch(url,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(response.status===401){token=await getMercadoLivreAccessToken(true);response=await fetch(url,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"})}return response}
async function predictDomain(q:string){try{const params=new URLSearchParams({q,limit:"1"});const response=await mlFetch(`https://api.mercadolibre.com/sites/MLB/domain_discovery/search?${params.toString()}`);if(!response.ok)return null;const data=await response.json();const suggestions:DomainSuggestion[]=Array.isArray(data)?data:[];return suggestions[0]||null}catch{return null}}
async function searchCatalog(q:string,domainId:string|null,offset:number,limit=30){const params=new URLSearchParams({status:"active",site_id:"MLB",q,limit:String(limit),offset:String(offset)});if(domainId)params.set("domain_id",domainId);const response=await mlFetch(`https://api.mercadolibre.com/products/search?${params.toString()}`);const data=await response.json();return{response,data}}
async function getBestCatalogOffer(productId:string){try{const response=await mlFetch(`https://api.mercadolibre.com/products/${encodeURIComponent(productId)}/items`);if(!response.ok)return null;const data=await response.json();const offers:MercadoLivreOffer[]=Array.isArray(data?.results)?data.results:[];const valid=offers.filter(o=>typeof o.item_id==="string"&&(!o.condition||o.condition==="new")&&typeof o.price==="number").sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));const best=valid[0];if(!best?.item_id||typeof best.price!=="number")return null;return{item_id:best.item_id,price:best.price,original_price:typeof best.original_price==="number"?best.original_price:null,currency_id:best.currency_id||"BRL",offers_count:offers.length}}catch{return null}}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function queryWords(q:string){return normalize(q).split(/\s+/).filter(w=>w.length>1)}
function matchCoverage(name:string,q:string){const title=normalize(name),words=queryWords(q);if(!words.length)return 0;const matched=words.filter(w=>title.includes(w)).length;return matched/words.length}
function relevanceScore(name:string,q:string){const title=normalize(name),query=normalize(q),words=queryWords(q);let score=0;if(title===query)score+=500;if(title.startsWith(query))score+=250;if(title.includes(query))score+=180;const coverage=matchCoverage(name,q);score+=coverage*160;for(const word of words){if(title.includes(word))score+=20;if(title.startsWith(word))score+=8}return score}
async function enrichProducts(products:MercadoLivreProduct[],q:string,basePosition:number):Promise<SearchRow[]>{return Promise.all(products.map(async(product,index)=>{const pictures=Array.isArray(product.pictures)?product.pictures.map(p=>p?.secure_url||p?.url||null).filter((v):v is string=>Boolean(v)):[];const features=Array.isArray(product.main_features)?product.main_features.map(f=>f?.text||f?.value_name||null).filter((v):v is string=>Boolean(v)).slice(0,3):[];const offer=product.id?await getBestCatalogOffer(product.id):null;return{id:product.id||null,name:product.name||null,status:product.status||null,domain_id:product.domain_id||null,image:pictures[0]||null,pictures,features,permalink:product.id?`https://www.mercadolivre.com.br/p/${product.id}`:null,offer_item_id:offer?.item_id||null,offer_price:offer?.price??null,offer_original_price:offer?.original_price??null,currency_id:offer?.currency_id||null,offers_count:offer?.offers_count??0,search_position:basePosition+index,relevance:relevanceScore(product.name||"",q),coverage:matchCoverage(product.name||"",q)}}))}
function dedupe(rows:SearchRow[]){const seen=new Set<string>();return rows.filter(r=>{const key=r.id||r.name||"";if(!key||seen.has(key))return false;seen.add(key);return true})}

export async function GET(request:Request){try{const q=new URL(request.url).searchParams.get("q")?.trim()||"";if(q.length<2)return NextResponse.json({ok:false,error:"Digite pelo menos 2 caracteres para pesquisar."},{status:400});const predicted=await predictDomain(q),domainId=predicted?.domain_id||null;let collected:SearchRow[]=[],total=0,scannedCatalogs=0;
for(const offset of [0,30,60]){const calls=[searchCatalog(q,null,offset,30)];if(domainId)calls.push(searchCatalog(q,domainId,offset,30));const batches=await Promise.all(calls);for(const {response,data} of batches){if(!response.ok)continue;const page:MercadoLivreProduct[]=Array.isArray(data?.results)?data.results:[];if(offset===0)total=Math.max(total,Number(data?.paging?.total||page.length));if(!page.length)continue;scannedCatalogs+=page.length;collected=collected.concat(await enrichProducts(page,q,offset));}collected=dedupe(collected);if(collected.length>=60)break}
const words=queryWords(q);const minCoverage=words.length>=5?0.6:words.length>=3?0.67:0.5;const relevant=collected.filter(p=>p.coverage>=minCoverage);const pool=relevant.length?relevant:collected.filter(p=>p.coverage>=0.5);const priced=pool.filter(p=>p.offer_item_id&&p.offer_price!=null).sort((a,b)=>b.relevance-a.relevance||a.search_position-b.search_position);const withoutPrice=pool.filter(p=>!(p.offer_item_id&&p.offer_price!=null)).sort((a,b)=>b.relevance-a.relevance||a.search_position-b.search_position);const enoughPriced=priced.length>=6;const results=(enoughPriced?priced:[...priced,...withoutPrice]).slice(0,12);
return NextResponse.json({ok:true,query:q,predicted_domain:predicted?.domain_id||null,predicted_domain_name:predicted?.domain_name||null,predicted_category:predicted?.category_id||null,predicted_category_name:predicted?.category_name||null,total,scanned_catalogs:scannedCatalogs,priced_results:priced.length,showing_only_priced:enoughPriced,strict_match:relevant.length>0,results})}catch(error){console.error("Erro ao pesquisar produtos do Mercado Livre",error);return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Erro interno ao pesquisar produtos."},{status:500})}}
