import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { getDb } from "@/lib/db";
export const dynamic="force-dynamic";
function money(v:number|string){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0)}
function status(v:string){return v==="approved"?"Pago":v==="rejected"?"Recusado":v==="cancelled"?"Cancelado":"Aguardando pagamento"}
export default async function SellerOrders(){const user=await getCurrentUser();if(!user)redirect("/entrar");const sql=getDb();const sellers=await sql`SELECT id,approval_status FROM sellers WHERE user_id=${Number(user.id)} LIMIT 1`;const seller=sellers[0] as any;if(!seller||seller.approval_status!=="approved")redirect("/minha-conta");const rows=await sql`SELECT o.id,o.payment_status,o.created_at,COUNT(oi.id)::int item_count,SUM(oi.subtotal) seller_total FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE oi.seller_id=${Number(seller.id)} GROUP BY o.id,o.payment_status,o.created_at ORDER BY o.created_at DESC`;return <main style={{minHeight:"100vh",background:"#f5f7fb",padding:"28px 16px",color:"#172554"}}><section style={{maxWidth:950,margin:"auto"}}><Link href="/vendedor" style={{color:"#2563eb",fontWeight:800,textDecoration:"none"}}>← Painel do vendedor</Link><h1 style={{fontSize:36}}>Pedidos da minha loja</h1>{!rows.length?<div style={card}>Sua loja ainda não possui pedidos.</div>:<div style={{display:"grid",gap:12}}>{rows.map((r:any)=><div key={r.id} style={{...card,display:"grid",gridTemplateColumns:"1fr auto",gap:16,alignItems:"center"}}><div><strong>Pedido #{r.id}</strong><div style={{fontSize:13,color:"#64748b",marginTop:5}}>{Number(r.item_count)} {Number(r.item_count)===1?"item":"itens"} • {status(String(r.payment_status))}</div></div><strong style={{fontSize:18}}>{money(r.seller_total)}</strong></div>)}</div>}</section></main>}
const card={background:"white",border:"1px solid #e2e8f0",borderRadius:14,padding:18,boxShadow:"0 5px 20px #00000008"};
