import { getDb } from "@/lib/db";
import { notFound,redirect } from "next/navigation";
import AdminSidebar from "../../../AdminSidebar";
export const dynamic="force-dynamic";
function makeSlug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}
function isValidImageUrl(value:string){if(!value)return true;try{const url=new URL(value);return url.protocol==="https:"||url.protocol==="http:";}catch{return false;}}
async function getCategory(id:number){const sql=getDb();const rows=await sql`SELECT id,name,slug,parent_id,active,image_url FROM categories WHERE id=${id} LIMIT 1`;return rows[0]||null;}
async function getParents(id:number){const sql=getDb();return sql`WITH RECURSIVE descendants AS (SELECT id FROM categories WHERE id=${id} UNION ALL SELECT c.id FROM categories c JOIN descendants d ON c.parent_id=d.id), tree AS (SELECT c.id,c.name,c.parent_id,c.name::text AS path,ARRAY[c.id] AS ids FROM categories c WHERE c.parent_id IS NULL AND c.id NOT IN (SELECT id FROM descendants) UNION ALL SELECT c.id,c.name,c.parent_id,(t.path||' › '||c.name)::text,t.ids||c.id FROM categories c JOIN tree t ON c.parent_id=t.id WHERE c.id NOT IN (SELECT id FROM descendants) AND NOT c.id=ANY(t.ids)) SELECT id,name,parent_id,path FROM tree ORDER BY path`;}
async function updateCategory(formData:FormData){"use server";const id=Number(formData.get("id"));const name=String(formData.get("name")||"").trim();const slugInput=String(formData.get("slug")||"").trim();const parentRaw=String(formData.get("parent_id")||"").trim();const parentId=parentRaw?Number(parentRaw):null;const imageUrl=String(formData.get("image_url")||"").trim();const active=formData.get("active")==="on";if(!Number.isInteger(id)||id<=0||!name)throw new Error("Categoria inválida.");if(!isValidImageUrl(imageUrl))throw new Error("Informe uma URL de imagem válida (http ou https).");if(parentId===id)throw new Error("Uma categoria não pode ser sua própria categoria superior.");const slug=makeSlug(slugInput||name);const sql=getDb();if(parentId){const invalid=await sql`WITH RECURSIVE descendants AS (SELECT id FROM categories WHERE id=${id} UNION ALL SELECT c.id FROM categories c JOIN descendants d ON c.parent_id=d.id) SELECT id FROM descendants WHERE id=${parentId} LIMIT 1`;if(invalid.length)throw new Error("Uma categoria não pode ser movida para dentro de uma de suas próprias subcategorias.");}await sql`UPDATE categories SET name=${name},slug=${slug},parent_id=${parentId},image_url=${imageUrl||null},active=${active},updated_at=NOW() WHERE id=${id}`;redirect("/admin/categorias");}
export default async function EditarCategoriaPage({params}:{params:Promise<{id:string}>}){const {id:raw}=await params;const id=Number(raw);if(!Number.isInteger(id)||id<=0)notFound();const category:any=await getCategory(id);if(!category)notFound();const parents:any[]=await getParents(id) as any[];return <main className="admin-shell"><AdminSidebar/><section className="admin-content"><header className="admin-header"><div><p className="eyebrow">ORGANIZAÇÃO</p><h1>Editar categoria</h1><p className="admin-subtitle">Altere o nome, imagem e organização da categoria.</p></div><a className="secondary-button" href="/admin/categorias">← Voltar</a></header><form action={updateCategory} className="product-form"><input type="hidden" name="id" value={category.id}/><section className="form-card"><div className="form-grid"><label className="field field-full"><span>Nome *</span><input name="name" required defaultValue={category.name}/></label><label className="field field-full"><span>Slug</span><input name="slug" defaultValue={category.slug||""}/></label><label className="field field-full"><span>Imagem/ícone da categoria</span><input name="image_url" type="url" defaultValue={category.image_url||""} placeholder="https://..."/><small style={{color:"#64748b"}}>Cole a URL de uma imagem própria da categoria. Se deixar vazio, a vitrine continuará usando o ícone automático.</small></label>{category.image_url?<div className="field field-full"><img src={category.image_url} alt={category.name} style={{width:110,height:90,objectFit:"contain",border:"1px solid #e2e8f0",borderRadius:12,background:"#fff",padding:8}}/></div>:null}<label className="field field-full"><span>Categoria superior</span><select name="parent_id" defaultValue={category.parent_id?String(category.parent_id):""}><option value="">Nenhuma — manter como categoria principal</option>{parents.map(p=><option key={p.id} value={p.id}>{p.path}</option>)}</select><small style={{color:"#64748b"}}>Você pode escolher qualquer nível existente. O sistema impede ciclos na hierarquia automaticamente.</small></label><div className="check-fields field-full"><label><input type="checkbox" name="active" defaultChecked={Boolean(category.active)}/> Categoria ativa</label></div></div></section><div className="form-actions"><a className="secondary-button" href="/admin/categorias">Cancelar</a><button className="primary-button" type="submit">Salvar alterações</button></div></form></section></main>;}
