"use client";

import { useState } from "react";

type Preview = { ok:boolean; type?:string; error?:string; product?:{ id?:string|null; catalog_product_id?:string|null; name?:string|null; status?:string|null; permalink?:string|null; price?:number|null; original_price?:number|null; pictures?:string[] }; automation?:{ note?:string; price?:boolean; item_access_status?:number|null; price_access_status?:number|null; catalog_fallback?:boolean } };

export default function ImportadorMercadoLivre() {
  const [link,setLink]=useState(""); const [loading,setLoading]=useState(false); const [preview,setPreview]=useState<Preview|null>(null);
  async function buscar(){ if(!link.trim())return; setLoading(true); setPreview(null); try { const response=await fetch(`/api/mercadolivre/import-preview?value=${encodeURIComponent(link.trim())}`); const data=await response.json(); setPreview(data); if(data?.ok&&data?.product){ const setValue=(name:string,value:string)=>{const el=document.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[name="${name}"]`);if(el)el.value=value;}; const hasAutomaticPrice=data?.automation?.price===true&&data.product.price!=null; const restricted=data?.automation?.item_access_status===403||data?.automation?.price_access_status===403; const itemId=data.product.id||""; const catalogId=data.product.catalog_product_id||""; setValue("name",data.product.name||""); setValue("marketplace_item_id",itemId); setValue("marketplace_product_id",catalogId); setValue("marketplace_reference_type",itemId?"item":catalogId?"catalog_product":data.type==="catalog_product"?"catalog_product":"item"); setValue("marketplace_url",data.product.permalink||link.trim()); setValue("imported_images",JSON.stringify(Array.isArray(data.product.pictures)?data.product.pictures:[])); setValue("price_source",hasAutomaticPrice?"automatic":"manual"); setValue("price_sync_status",hasAutomaticPrice?"ok":restricted?"restricted":"pending"); setValue("price_checked_at",new Date().toISOString()); setValue("regular_price",data.product.original_price!=null?String(data.product.original_price):""); setValue("promo_price",data.product.price!=null?String(data.product.price):""); }} catch {setPreview({ok:false,error:"Não foi possível consultar o Mercado Livre agora."});} finally {setLoading(false);} }
  return <section className="form-card ml-import-card"><div className="ml-import-heading"><div><p className="eyebrow">IMPORTAÇÃO AUTOMÁTICA</p><h2>Buscar no Mercado Livre</h2><p className="admin-subtitle">Cole o link do produto. O Radar preencherá automaticamente os dados que a API disponibilizar.</p></div><span className="ml-badge">Mercado Livre conectado</span></div><div className="ml-import-row"><input type="text" value={link} onChange={(e)=>setLink(e.target.value)} placeholder="Cole aqui o link do produto do Mercado Livre"/><button type="button" className="primary-button" onClick={buscar} disabled={loading||!link.trim()}>{loading?"Buscando...":"Buscar produto"}</button></div>{preview&&!preview.ok&&<div className="ml-result ml-error"><strong>Não foi possível importar.</strong><span>{preview.error}</span></div>}{preview?.ok&&preview.product&&<div className="ml-result ml-success">{preview.product.pictures?.[0]?<img src={preview.product.pictures[0]} alt="Prévia do produto"/>:null}<div><strong>{preview.product.name}</strong><span>{preview.type==="catalog_product"?"Produto de catálogo":"Anúncio individual"} · {preview.product.status==="active"?"Ativo":preview.product.status||"Status não informado"}</span>{preview.automation?.note?<small>{preview.automation.note}</small>:null}</div></div>}</section>;
}
